// Code generated by "stringer -type fileExists"; DO NOT EDIT.

package dotconfig

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotExists-0]
	_ = x[BaseExists-1]
	_ = x[FileExists-2]
}

const _fileExists_name = "NotExistsBaseExistsFileExists"

var _fileExists_index = [...]uint8{0, 9, 19, 29}

func (i fileExists) String() string {
	if i < 0 || i >= fileExists(len(_fileExists_index)-1) {
		return "fileExists(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _fileExists_name[_fileExists_index[i]:_fileExists_index[i+1]]
}
